#!/usr/bin/env python3
from __future__ import annotations

import argparse
from pathlib import Path

from ipynb_json import code_cell, md_cell, new_notebook, write_notebook


def _build_cells(*, title: str, include_open_questions: bool) -> list[dict]:
    cells: list[dict] = []

    cells.append(
        md_cell(
            f"# {title}\n\n"
            "Prototype notebook scaffold generated by `$exposition-to-notebook`.\n"
            "Edit cells so a kernel restart + “Run all” completes cleanly.\n"
        )
    )

    if include_open_questions:
        cells.append(
            md_cell(
                "## Open Questions / TODO\n\n"
                "- [ ] What are the exact inputs/outputs?\n"
                "- [ ] What assumptions/constraints matter?\n"
                "- [ ] What datasets or parameters are required?\n"
            )
        )

    cells.append(md_cell("## Goal\n\nDescribe what this notebook should produce and how to judge success.\n"))

    cells.append(
        md_cell(
            "## Setup\n\n"
            "- Prefer minimal dependencies; document any non-stdlib deps.\n"
            "- Keep cells idempotent (no hidden state).\n"
            "- Seed randomness for reproducibility.\n"
        )
    )

    cells.append(
        code_cell(
            "import platform\n"
            "import random\n"
            "import sys\n"
            "\n"
            "print(\"Python:\", sys.version)\n"
            "print(\"Platform:\", platform.platform())\n"
            "\n"
            "SEED = 0\n"
            "random.seed(SEED)\n"
            "\n"
            "try:\n"
            "    import numpy as np  # type: ignore\n"
            "\n"
            "    np.random.seed(SEED)\n"
            "except Exception:\n"
            "    np = None\n"
        )
    )

    cells.append(
        md_cell(
            "## Background / Exposition\n\n"
            "Paste or summarize the source exposition here (keep equations in LaTeX).\n"
        )
    )

    cells.append(md_cell("## Implementation\n\nImplement the computable core as reusable functions.\n"))

    cells.append(
        code_cell(
            "from __future__ import annotations\n"
            "\n"
            "from dataclasses import dataclass\n"
            "from typing import Any\n"
            "\n"
            "\n"
            "# TODO: Replace stubs with real implementations.\n"
            "def core(inputs: Any) -> Any:\n"
            "    \"\"\"Compute the primary output from the exposition.\"\"\"\n"
            "    return inputs\n"
        )
    )

    cells.append(md_cell("## Validation\n\nAdd sanity checks and a few key invariants as tests.\n"))
    cells.append(code_cell("# TODO: Replace with real tests.\nassert True\n"))

    cells.append(md_cell("## Demo / Experiments\n\nShow usage, generate plots/tables, and interpret results.\n"))
    cells.append(code_cell("# TODO: Call `core(...)` with a realistic example.\nresult = core({\"example\": 1})\nresult\n"))

    cells.append(md_cell("## Conclusion\n\nSummarize what works, limitations, and next steps.\n"))

    return cells


def main() -> None:
    parser = argparse.ArgumentParser(description="Create a product-ready notebook scaffold (.ipynb).")
    parser.add_argument("--out", required=True, help="Output .ipynb path")
    parser.add_argument("--title", required=True, help="Notebook title")
    parser.add_argument(
        "--no-open-questions",
        action="store_true",
        help="Do not include the 'Open Questions / TODO' section",
    )
    args = parser.parse_args()

    notebook = new_notebook(_build_cells(title=args.title, include_open_questions=not args.no_open_questions))
    out_path = write_notebook(args.out, notebook)
    print(f"Wrote: {out_path}")


if __name__ == "__main__":
    main()

